PieShop/Models/Pie.cs
using System.ComponentModel.DataAnnotations;

namespace PieShop.Models
{
    public class Pie
    {
        public int PieId { get; set; }
        public string Name { get; set; } = string.Empty;
        public string? ShortDescription { get; set; }
        public string? LongDescription { get; set; }
        public string? AllergyInformation { get; set; }
        public decimal Price { get; set; }
        public string? ImageUrl { get; set; }
        public string? ImageThumbnailUrl { get; set; }
        public bool IsPieOfTheWeek { get; set; }
        public bool InStock { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; } = default!;
    }
}

PieShop/Controllers/PieController.cs
using Microsoft.AspNetCore.Mvc;
using PieShop.Models;
using PieShop.ViewModels;

namespace PieShop.Controllers
{
    public class PieController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IPieRepository _pieRepository;
        public PieController(IPieRepository pieRepository,ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
            _pieRepository = pieRepository;
        }
        public IActionResult List()
        {
            //ViewBag.currentCategory = "show data";
            //return View(_pieRepository.AllPies);

            PieListViewModel pieListViewModel = new PieListViewModel(_pieRepository.AllPies,"show data");
            return View(pieListViewModel);
            
        }
        public IActionResult Details(int id)
        {
           var pie = _pieRepository.GetPieById(id);
            if(pie==null)
            {
                return NotFound();
            }
            return View(pie);


        }
    }
}

PieShop/Views/Pie/Details.cshtml
@model Pie

<h3 class="my-5">
    @Model.Name
</h3>

<div class="row gx-5">
    <img alt="@Model.Name" src="@Model.ImageUrl" class="img-fluid col-5" />
    <div class="col-7">
        <h4>@Model.ShortDescription</h4>
        <p>@Model.LongDescription</p>
        <h3 class="pull-right">@Model.Price.ToString("c")</h3>
        <div class="addToCart">
            <p class="button">

            </p>
        </div>
    </div>
</div>

PieShop/Views/Pie/List.cshtml
@model PieShop.ViewModels.PieListViewModel
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Pie Shop!</title>
</head>
<body>
    <div class="row row-cols-1 row-cols-md-3 g-4">

        @foreach (var pie in Model.Pies)
        {
            <div class="col">
                <div class="card pie-card">
                    <img src="@pie.ImageThumbnailUrl" class="card-img-top" alt="@pie.Name">
                    <div class="card-body pie-button">
                        <h4 class="d-grid">
                        </h4>

                        <div class="d-flex justify-content-between mt-2">
                            <h2 class="text-start">
                                <a class="pie-link" asp-controller="Pie" asp-action="Details" asp-route-id="@pie.PieId">@pie.Name</a>
                            </h2>
                            <h5 class="text-nowrap">
                                @pie.Price.ToString("c")
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>